services:
  postgres:
    container_name: user_management_system_nextjs
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: ums_db
    volumes:
      - postgres:/var/lib/postgresql/data
    restart: unless-stopped
  mail-dev:
    container_name: mail_dev_ums
    image: maildev/maildev
    ports:
      - "1080:1080"
      - "1025:1025"

volumes:
  postgres:
